builds:
  # List of builds
- # First Build
  env:
    - CGO_ENABLED=0
  main: ./uptime_metric_check/main.go
  binary: bin/sensu-go-uptime-metrics
- main: ./uptime_status_check/main.go
  binary: bin/sensu-go-uptime-status
  goos:
    - darwin
    - freebsd
    - linux
    - netbsd
    - solaris
    - windows
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
      # TODO: add freebsd/arm support to gopsutil
    - goos: freebsd
      goarch: arm

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha256-checksums.txt"

archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md